### ISSUE TITLE
Method .as_matrix will be removed in a future version. Use .values instead.

### ISSUE THREAD

**Issue by erstrong** [david-cortes/contextualbandits#1]
The utilities module uses the as_matrix method three times. Fitting a model generates the warning: 

```
<path>\contextualbandits\utils.py:85: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
 X=X.as_matrix()
```

The method is also used on lines 97 and 482.

**Comment by david-cortes** [comment]
Thanks for reporting this problem! Fixed in the master branch, will be eventually included in the pip version in a future release.
