### ISSUE TITLE
Model Saving and Incremental Training

### ISSUE THREAD

**Issue by wenruij** [david-cortes/contextualbandits#11]
@david-cortes 
Is there a way for the incremental training?  That should be an important requirement

**Comment by david-cortes** [comment]
> @david-cortes
> Is there a way for the incremental training? That should be an important requirement

Sure there is: most models admit an initialization parameter `batch_train = True`. After that, you have to fit them to batches of data using `.partial_fit` instead of `.fit`. You can then save models using the package `dill` as exemplified in the `README.md` file.

**Comment by wenruij** [comment]
@david-cortes thanks, that would be great
