### ISSUE TITLE
Ques: GPU or CPU ops?

### ISSUE THREAD

**Issue by joehoeller** [david-cortes/contextualbandits#14]
Is this framework GPU bound or CPU bound operations?

**Comment by david-cortes** [comment]
It takes classifier objects as arguments and leaves all the model fitting to them, so that depends on what you pass as classifiers.

**Comment by joehoeller** [comment]
I took a look at somethings, for example, you have fit() which is a SciKit Learn wrapper (CPU bound). 

You have an amazing framework with the ability to add arms etc, but let me investigate further to see where I might be able to replace some behind the scenes functions with PyCUDA, Numba, CuPy or H2O4GPU which is a SciKit Learn drop in replacement. 

I’ll eval which one is best because mixing too many frameworks causes non determinism. With that being said, Numba wrappers with CuPy or SciKitCUDA with CuPy might be what’s needed for about 20x speed up here. 

Let me play with something’s and get back to you.
