### ISSUE TITLE
AttributeError: '_BetaPredictor' object has no attribute 'partial_fit'

### ISSUE THREAD

**Issue by xinyuewang1** [david-cortes/contextualbandits#15]
Hi, first want to thank you for sharing this marvellous job. 

I'm trying to follow the example on [notebook](https://nbviewer.jupyter.org/github/david-cortes/contextualbandits/blob/master/example/online_contextual_bandits.ipynb) 3.3 Streaming models
When using `softmax_explorer.partial_fit()`, I get error as below

> Traceback (most recent call last):
>   File "/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-2-a95a64a8e58a>", line 1, in <module>
>     runfile('/Users/user/projects/project/project/test/test_adressa_with_contextual_bandit_agent.py', wdir='/Users/user/projects/project/project/test')
>   File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
>     pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
>   File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "/Users/user/projects/project/project/test/test_adressa_with_contextual_bandit_agent.py", line 64, in <module>
>     np.array(current_batch_rewards))
>   File "/Users/user/projects/project/project/example_agents/contextual_bandits.py", line 86, in re_train
>     self.selected_model = self.selected_model.partial_fit(X=states, a=actions, r=rewards)
>   File "/anaconda3/envs/project/lib/python3.7/site-packages/contextualbandits/online.py", line 210, in partial_fit
>     self._oracles.partial_fit(X, a, r)
>   File "/anaconda3/envs/project/lib/python3.7/site-packages/contextualbandits/utils.py", line 598, in partial_fit
>     Parallel(n_jobs=self.njobs, verbose=0, require="sharedmem")(delayed(self._partial_fit_single)(choice, X, a, r) for choice in range(self.n))
>   File "/anaconda3/envs/project/lib/python3.7/site-packages/joblib/parallel.py", line 934, in __call__
>     self.retrieve()
>   File "/anaconda3/envs/project/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
>     self._output.extend(job.get(timeout=self.timeout))
>   File "/anaconda3/envs/project/lib/python3.7/multiprocessing/pool.py", line 657, in get
>     raise self._value
>   File "/anaconda3/envs/project/lib/python3.7/multiprocessing/pool.py", line 121, in worker
>     result = (True, func(*args, **kwds))
>   File "/anaconda3/envs/project/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 567, in __call__
>     return self.func(*args, **kwargs)
>   File "/anaconda3/envs/project/lib/python3.7/site-packages/joblib/parallel.py", line 225, in __call__
>     for func, args, kwargs in self.items]
>   File "/anaconda3/envs/project/lib/python3.7/site-packages/joblib/parallel.py", line 225, in <listcomp>
>     for func, args, kwargs in self.items]
>   File "/anaconda3/envs/project/lib/python3.7/site-packages/contextualbandits/utils.py", line 608, in _partial_fit_single
>     self.algos[choice].partial_fit(xclass, yclass, classes = [0, 1])
> AttributeError: '_B

etaPredictor' object has no attribute 'partial_fit'

What being passed in _partial_fit_single is as below:

> self.algos: [<contextualbandits.utils._BetaPredictor object at 0x1a1dd01518>, <contextualbandits.utils._BetaPredictor object at 0x1a20aaff98>] 
> choice: 1

Any idea why? Any help will be appreciated.
Thanks in advance. 🌻

**Comment by david-cortes** [comment]
If you want to use `.partial_fit`, you need to pass `batch_train = True` to the constructor. But there's another bug that will prevent you from doing that which I'll fix now.

**Comment by david-cortes** [comment]
Update pushed to `pip`, please update to version 0.1.7.8.
