### ISSUE TITLE
Is There A Message Board For This?

### ISSUE THREAD

**Issue by kivo360** [david-cortes/contextualbandits#16]
I'm extremely new to the subject of contextual bandits and reinforcement learning. What I am interested in is how people use contextual bandits for advertising at scale. How do you average the rewards out?

**Comment by david-cortes** [comment]
I don’t think I can help you with that. Don’t know of any user groups or forums dedicated to it. Perhaps you can try reddit.

**Comment by kivo360** [comment]
Never mind, I was able to figure something out.
