### ISSUE TITLE
Doubt with documentation regarding EpsilongGreedy 'assume_unique_reward' parameter

### ISSUE THREAD

**Issue by renan-cunha** [david-cortes/contextualbandits#18]
On the EpsilonGreedy algorithm, the documentation says that:

[`assume_unique_reward (bool) – Whether to assume that only one arm has a reward per observation. If set to False, whenever an arm receives a reward, the classifiers for all other arms will be fit to that observation too, having negative label.`
](https://contextual-bandits.readthedocs.io/en/latest/index.html#contextualbandits.online.EpsilonGreedy)

But from the code, it appears it is the other way. Am I misunderstanding something?

https://github.com/david-cortes/contextualbandits/blob/719c2c9028b79c7071bcf0f243e3a7b26b490d91/contextualbandits/utils.py#L613-L625

**Comment by david-cortes** [comment]
Yes, thanks for noticing -  it's the other way around, I need to update the documentation.
