### ISSUE TITLE
Pretty sure this should have alpha multiplied into it

### ISSUE THREAD

**Issue by adamklein** [david-cortes/contextualbandits#19]
(btw, thx for the awesome work!!)

https://github.com/david-cortes/contextualbandits/blob/78ea43ae42e1888ae0e172ef452e1868e89c5f61/contextualbandits/utils.py#L819

Trying to line up with algo 1 in http://proceedings.mlr.press/v15/chu11a/chu11a.pdf

**Comment by adamklein** [comment]
Err, I see, since alpha is same across all arms, and sqrt applied as well, doesn't matter. NVM!

**Comment by adamklein** [comment]
Actually, spoke to soon. I get a different set of online predictions if alpha and sqrt are used, which makes sense. Is there a theoretical justification for excluding them in this implementation?

**Comment by david-cortes** [comment]
Oh yeah I messed that up after the last update, will fix. Thanks for the bug report.

**Comment by david-cortes** [comment]
Fixed now, please update to 0.1.8.2.

**Comment by david-cortes** [comment]
Actually still not.

**Comment by david-cortes** [comment]
Ok, fixed now in 0.1.8.3.
