### ISSUE TITLE
Bibtex_data.txt

### ISSUE THREAD

**Issue by htcml** [david-cortes/contextualbandits#20]
Where is Bibtex_data.txt located?

**Comment by david-cortes** [comment]
It's taken from the [extreme classification repository](http://manikvarma.org/downloads/XC/XMLRepository.html) as mentioned in the notebooks.

**Comment by glebkiselev** [comment]
the direct link has been moved to http://manikvarma.org/downloads/XC/XMLRepository.html

**Comment by AbrarHossainHimself** [comment]
How to make sense of the bibtex_data.txt file. It just seems like a bunch of random numbers.

**Comment by david-cortes** [comment]
> How to make sense of the bibtex_data.txt file. It just seems like a bunch of random numbers.

You can check the source for more info.
