### ISSUE TITLE
Single Model

### ISSUE THREAD

**Issue by htcml** [david-cortes/contextualbandits#22]
Are there any implemented algorithms in this library which uses a single unified model for all arms?

**Comment by david-cortes** [comment]
No, there isn't any yet. Also the library doesn't use arm features.

**Comment by htcml** [comment]
@david-cortes Since you are an expert in bandit algorithms, can you point out some papers about unified models? Is it worthwhile to pursue the unified model approach?

**Comment by david-cortes** [comment]
No idea. From my own experiments, when trying to do a single model with arm features and no similarity info, I haven't got any uplift over a naive policy which would always use argmax with no exploration strategy.
