### ISSUE TITLE
Need more understanding for the method add_arm

### ISSUE THREAD

**Issue by arunbhaskarw10** [david-cortes/contextualbandits#25]
Please add more documentation or mention here on how to use the method and how it will work with or without existing training data when adding a new arm.

**Comment by david-cortes** [comment]
It's used when you want to add a new arm to an object which has already been fit to data which didn't initially include it, and it works in the same way as with the initial arms: that is, if you used `beta_prior`, it will use it for the predictions; if you used `smoothing`, will use it for the predictions while assuming the regular outputs from the model are zero or some small number; and if you use neither, will assume the arm always gets a prediction of zero until you fit it to data from that arm (so in this last case it's not going to be chosen until you later fit it to data from that arm collected externally).

The rest is as explained in the documentation - you can pass counts which will be used for `beta_prior` and `smoothing`, can pass data to use with `refit_buffer` next time you call `partial_fit`, or can pass a fitted classifier, or all of them together.
