### ISSUE TITLE
Bibtex_data In Examples?

### ISSUE THREAD

**Issue by ahlusar1989** [david-cortes/contextualbandits#28]
Hi @david-cortes,

I was wondering if you had the example data set that is use in your examples?

That or a reference would be much appreciated.

**Comment by david-cortes** [comment]
It's taken from the extreme classification repository as mentioned in the notebooks: http://manikvarma.org/downloads/XC/XMLRepository.html

**Comment by ahlusar1989** [comment]
Thank you.
