### ISSUE TITLE
Regarding Bibtex data in example

### ISSUE THREAD

**Issue by ahlusar1989** [david-cortes/contextualbandits#29]
Hi @david-cortes, 

Do you have an example data set or reference to this that is used in your simulation?

Thank you,

Saran

**Comment by david-cortes** [comment]
@ahlusar1989 you asked the same thing before: https://github.com/david-cortes/contextualbandits/issues/28

**Comment by ahlusar1989** [comment]
Apologies - I missed this earlier.
