### ISSUE TITLE
Is there any Concern over Adding costsensitive Package as a Dependency?

### ISSUE THREAD

**Issue by YanjieHe** [david-cortes/contextualbandits#34]
Just out of curiosity, is there any concern over adding the `costsensitive` package to the `install_requires` list? The package could be used by users, but it was not installed automatically.

```py
try:
    from costsensitive import _BinTree
except:
    raise ValueError("This functionality requires package 'costsensitive'.\nCan be installed with 'pip install costsensitive'.")
```

**Comment by david-cortes** [comment]
Installation troubles - for example, costsensitive doesn't work with python2, and some people have reported installation issues. Since most users of this package don't use the functionality that calls for it, I preferred to leave it as optional.

**Comment by YanjieHe** [comment]
Got it. That makes sense.
