### ISSUE TITLE
extra param in example/policy_evaluation.ipynb

### ISSUE THREAD

**Issue by sroy2** [david-cortes/contextualbandits#39]
I figured commenting here would be easier than forking with a pull request.

The final example (using Mediamill_data.txt) has an extra parameter `update_freq = 5`

I'm guessing this is just a leftover artifact but couldn't find any commit version of `evaluateRejectionSampling` that had it? I don't believe removing it substantially changes any of the points made in the tutorial, but the cell result did change from ~`(0.4028, 422)` to  ~`(0.4539, 445)`. 

Great library btw!

**Comment by david-cortes** [comment]
Thanks for the bug report. This parameter (number of observations after which to make an update) was removed in favor of a faster batch size (number of observations for which to make predictions, with the number of observations for the update matching to the ones that were not rejected in the batch). Perhaps I should add it back.

**Comment by sroy2** [comment]
Both have their benefits, I don't know how much work it would be to put the argument back. I've barely scratched the surface of your paper, but it feels like freq would be useful if you already knew something about how often your policy changed. That said, if it were my repo, unless it's fairly trivial to implement I would personally wait until the feature was requested xD
