### ISSUE TITLE
Reproducibility issue with current branch of library?

### ISSUE THREAD

**Issue by sroy2** [david-cortes/contextualbandits#42]
Hi,  

A group I was in tried to reproduce some of the results from the paper associated with this repo. 
To be honest, it was a bit more rushed than I'd like, there is probably a fair amount we could have done better by reaching out, I don't think there are any really significant findings - except we did find some curious behavior when comparing the cython vs pure-python implementation of some algorithms. We kind of ran out of time to isolate what was causing the change, we mainly noticed it because one of the group members was having issues with the cython and decided to use the python-pure version.

I was able to reproduce his results (comparing our own implementation, contextual-bandits 0.1.8.5 (matched), and contextual-bandits 0.3.13 (didn't match)). The link to the repo/paper is below - Figure 4 under Section 3.2.1 highlights the issue. 

https://github.com/MrinalJain17/ml-tools-project/blob/main/Contextual_Bandit_Comparison.pdf

I believe one of the main reasons why we were unable to completely reproduce the original paper may stem from this issues. Having some group members using different environments (versions of the library) quite possibly skewed some of our findings and isn't really addressed in our write-up. 

That said, I hope you have better luck figuring out what exactly is changing the current branch's behavior. Considering we implemented the ContextualAdaptiveGreedy algorithm from scratch and it tracked the 0.1.8.5 version - I'm assuming the problem isn't there...

**Comment by david-cortes** [comment]
Thanks for the report. Among many things, the current version has quite different default hyperparameters, with the new ones giving worse results in the BibTeX dataset, so it’s quite expected that the results would deteriorate like that. Apart from that, `AdaptiveGreedy` can have a lot of variation in performance from one run to another, so it’s possible that it ran into 1 unlucky run in the tests that would give much lower average performance.

I'm still able to achieve similar results with the current branch (at least for BibTeX) using different hyperparameters so I guess most of the difference comes from the default hyperparameters.
