### ISSUE TITLE
Import error: Cyclic dependency

### ISSUE THREAD

**Issue by aadirupa** [david-cortes/contextualbandits#43]
I am getting the following error in the __init__.py of linreg

ImportError: cannot import name '_wrapper_double' from partially initialized module 'contextualbandits.linreg' (most likely due to a circular import) (C:\...\python\contextualbandits-master\contextualbandits\linreg\__init__.py)

Is there an easy fix to this?

**Comment by david-cortes** [comment]
A couple questions:
* How did you install this package?
* Which Python version are you using?
* Are you trying to import `linreg` directly?
* Are you running the python process in the same directory from where this package was installed?
