### ISSUE TITLE
How to change the reward to continous interval?

### ISSUE THREAD

**Issue by musram** [david-cortes/contextualbandits#45]
Is there any way, I can change the reward from binary {0,1} to continuous [0,1[?

**Comment by david-cortes** [comment]
No, for the time being this package is only meant to work with binary rewards.

**Comment by subhambiswas-angelone** [comment]
what is an example of binary rewards vs continuous rewards?

**Comment by david-cortes** [comment]
> what is an example of binary rewards vs continuous rewards?

The question in the first post describes that.
