### ISSUE TITLE
Question regarding using contextual bandits for Learning-To-Rank

### ISSUE THREAD

**Issue by NikhilKothari** [david-cortes/contextualbandits#49]
Hey,

I want to use MAB in an LTR problem. Can you help me figure out which algorithm to use and a little about how to use it?
(a beginner in MAB I am)

I'm thinking of using the functionality for _ranking top-N arms instead of always picking the single best one_.
Any suggestion would help. Thanks in advance.

**Comment by david-cortes** [comment]
That’s the part where you’re supposed to do a literature review, use your skills, do experiments, and get creative. This library models a specific problem which you can find in the documentation – how to use it for a different problem domain is up to you and that is an open-ended problem.
