### ISSUE TITLE
Need more understanding for the method beta_prior

### ISSUE THREAD

**Issue by subhambiswas-angelone** [david-cortes/contextualbandits#55]
I have a system in which it does campaign allocation.
I have 5 campaigns to be sent to user , its now random allocation and later will test with epsilon greedy approach .
I am using Contextual Bandit in this problem with understanding of customers and campaign performance in previous runs or policies
I am not understanding beta_priors.

This part,"Can also pass different priors per arm, in which case they should be passed as a list of tuples. This parameter can have a very large impact in the end results, and it’s recommended to tune it accordingly - scenarios with low expected reward rates should have priors that result in drawing small random numbers, whereas scenarios with large expected reward rates should have stronger priors and tend towards larger random numbers. Also, the more arms there are, the smaller the optimal expected value for these random numbers."

**Comment by david-cortes** [comment]
You can refer to the documentation and the references for more information.
