### ISSUE TITLE
How to deal with this Scenario while applying CB techniques

### ISSUE THREAD

**Issue by subhambiswas-angelone** [david-cortes/contextualbandits#57]
I have ad campaigns to be sent and their conversion ratio ie click to send ratio which is success.
I have lets say 5 different types of campaigns ie 5 n-choices (arms) but have 6 labels that is 5 labels and another label which is not success (not clicked) at all. I have this not clicked label in maximum case. How to convert this problem into multi label Classification cause this has highly  imbalanced labels

**Comment by david-cortes** [comment]
This is a software issue tracker, not a free consultancy. You can start by reviewing the literature in the references and doing your own google searches.

**Comment by subhambiswas-angelone** [comment]
Its okay if you dont want to answer, but can you delete this ?
