### ISSUE TITLE
topN inputs clarification

### ISSUE THREAD

**Issue by Shriaachar** [david-cortes/contextualbandits#65]
Hi,
To get topN we are passing parameters  X and n, As mentioned X is an array of n_samples and n_features. Does n_samples and n_features have any significance or simply represents the size of an array ?
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/114223366/225824935-5f9a0ca2-88f9-4955-901b-15184ad71907.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/114223366/225824936-4f38f0fb-4abc-41f5-84b3-f72bc73acadd.png)

**Comment by david-cortes** [comment]
It represents the dimensions, which in turn determine what each axis is supposed to refer to. You can check scikit-learn's glossary for a deeper explanation.

**Comment by MounikaMadan** [comment]
Hi,
I could see n_samples and n_features represents the dimensions of X, but is there any correlation between 'n' in n_samples , n_features and parameter n for topN function.

**Comment by david-cortes** [comment]
> Hi, I could see n_samples and n_features represents the dimensions of X, but is there any correlation between 'n' in n_samples , n_features and parameter n for topN function.

No, that's just a coincidence.
