### ISSUE TITLE
warm_start for online policy

### ISSUE THREAD

**Issue by jordantkohn** [david-cortes/contextualbandits#66]
I don't see how the warm_start parameter in _BasePolicy changes the behavior of fit().

When warm_start = True in _BasePolicy.fit(), use_warm can become True.
use_warm is then passed to _OneVsRest's instantiation as parameter warm, where it does not appear inside the class definition.

Am I missing something?

**Comment by david-cortes** [comment]
Yes, thanks for the bug report. This was a vestige of older code that I've forgotten to remove. It currently doesn't make any difference as passing `warm_start=True` to the underlying base estimator would suffice. PR to remove it would be welcome.
