### ISSUE TITLE
Getting error while importing packages

### ISSUE THREAD

**Issue by mohit93725** [david-cortes/contextualbandits#70]
![Screenshot from 2024-08-12 10-55-56](https://github.com/user-attachments/assets/3ac91c56-86ed-45da-b7b5-4a5bf2f9ae6b)

**Comment by david-cortes** [comment]
I am unable to reproduce the issue.

* How did you trigger this error? Are you able to provide some sample code to trigger it?
* How did you install this package?
* Are using the latest version of this package? Currently this is 0.3.21.
