### ISSUE TITLE
Missing input argument in call to _check_beta_prior_single() 

### ISSUE THREAD

**Issue by VJvR** [david-cortes/contextualbandits#76]
Missing input argument "nchoices" in [this line](https://github.com/david-cortes/contextualbandits/blob/master/contextualbandits/utils.py#L151).

**Comment by VJvR** [comment]
Or, input argument 'nchoices' should be removed from the function definition [here](https://github.com/david-cortes/contextualbandits/blob/master/contextualbandits/utils.py#L155).

**Comment by david-cortes** [comment]
Thanks again for the bug report - this time it should be fixed.
