### ISSUE TITLE
TopN probabilidades?

### ISSUE THREAD

**Issue by fmafelipe** [david-cortes/contextualbandits#77]
Hello, I saw that you have added a new function to obtain the TopN arms, I would like to know if it is possible to obtain the corresponding probabilities of these arms or some similar value for any of the models.

**Comment by david-cortes** [comment]
Yes, most online policies have a method `decision_function` which should give what you want.

**Comment by fmafelipe** [comment]
As in the `predict` method you have the `exploration`parameter, is there something to simulate for the `TopN` and `decision_function` method?

**Comment by david-cortes** [comment]
I'm not sure what you mean to ask, but there are docs for all methods and functions in the readthedocs link.

If you mean to ask "give a probability distribution from which to choose the best arm" like other libraries do, then: no, the frameworks here don't work like that.
